### ISSUE TITLE
📱 Android App

### ISSUE THREAD

**Issue by tbsbdr** [opencloud-eu/Roadmap#16]
- ✅ iOS App available in App Store see https://github.com/opencloud-eu/Roadmap/issues/50 App Store: https://apps.apple.com/de/app/id6743121005
- 🏗️ Android App available in Play Store https://play.google.com/store/apps/details?id=eu.opencloud.android

Note: I split the issue into 2 tickets to reflect, that the iOS App is already released. This ticket is from now on only about Android.

**Comment by michaelstingl** [comment]
OpenCloud ⁦team announced the first public test flight of the iOS app: https://testflight.apple.com/join/2F5wWTGV 🎉⁦

**Comment by ahaodev** [comment]
Is there an Android client?

**Comment by tbsbdr** [comment]
@RUANHAOANDROID Android is planned until end of Q2/2025

**Comment by siblingsofthevoid** [comment]
Are there any plans to also make these apps available on alternative app stores (e.g. Fdroid on android or AltStore on iOS)?

**Comment by Lka1988** [comment]
Offering an alternate download from somewhere other than the play store (like Fdroid), or even just an apk file here on github, would be beneficial for those of us who want to avoid the play store.

**Comment by simon-verbois** [comment]
> @RUANHAOANDROID Android is planned until end of Q2/2025

Hello,

Any news of the android app ?

Br

**Comment by tbsbdr** [comment]
@simon-verbois we are currently in the QA phase, so I assume the release will be in July, I'll keep you posted.

**Comment by gardar** [comment]
In the meantime, it's possible to use the Owncloud android app by adding the owncloud android app to the OIDC client configuration as described here: https://github.com/opencloud-eu/docs/blob/cd9d0e0970140734a77c3bffcbae00f73663f4bf/static/env-vars/idp_readme.md#custom-clients

```
    - id: e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD
      name: ownCloud Android App
      trusted: false
      secret: ""
      redirect_uris:
        - oc://android.owncloud.com
      post_logout_redirect_uris:
        - oc://android.owncloud.com
      origins: []
      application_type: native
```

You also need to spoof the owncloud version in /capabilites - I'm doing it in my Caddy reverse proxy like this:

```
opencloud.example.tld {

        # Match Android ownCloud client requests for /capabilities
        @androidCapabilities {
                header User-Agent *ownCloud-android*
                path /ocs/v1.php/cloud/capabilities /ocs/v2.php/cloud/capabilities
        }
        handle @androidCapabilities {
                header Content-Type application/json
                respond `{
                        "ocs": {
                                "meta": { "status": "ok", "statuscode": 100, "message": "OK" },
                                "data": {
                                        "version": {
                                                "major": 10,
                                                "minor": 13,
                                                "micro": 0,
                                                "string": "10.13.0",
                                                "edition": ""
                                        },
                                        "capabilities": {}
                                }
                        }
                }` 200
        }

        # Default reverse proxy for everything else
        reverse_proxy 198.51.100.0:9200
}
```

But it's also possible to do it with traefik in the opencloud-compose if you use that. Just create the two files below and update your .env to include the override. ( `COMPOSE_FILE=docker-compose.yml:weboffice/collabora.yml:traefik/android-spoof.yml` )

traefik/android-spoof.yml
```
version: "3.8"

services:
  traefik:
    volumes:
      - ./traefik/extra-config/spoof-android.yml:/etc/traefik/dynamic/spoof-android.yml:ro
    labels:
      - traefik.http.routers.opencloud.middlewares=spoof-android-version@file

```

traefik/extra-config/spoof-android.yml
```
http:
  middlewares:
    spoof-android-version:
      headers:
        customResponseHeaders:
          oc-version: "10.0.0"

```

**Comment by ObrellusRex** [comment]
> In the meantime, it's possible to use the Owncloud android app

The ownCloud Android App checks server version during setup and will not let me add my OpenCloud Server due to: `Your server version is lower than 10`

**Comment by gardar** [comment]
> > In the meantime, it's possible to use the Owncloud android app
> 
> The ownCloud Android App checks server version during setup and will not let me add my OpenCloud Server due to: `Your server version is lower than 10`

You are absolutely right, I forgot to mention that I'm spoofing the owncloud version too. Please see my updated comment above how to work around that issue.

**Comment by juan11perez** [comment]
@gardar 
thank you for sharing this. I followed the instructions but im getting "unexpected HTTP response: 400. Please check connection and try again"

i can login no problem on the phone browser, but when is redirected from the owncloud app to sigin it throws the error.

**Comment by gardar** [comment]
> @gardar 
> thank you for sharing this. I followed the instructions but im getting "unexpected HTTP response: 400. Please check connection and try again"
> 
> i can login no problem on the phone browser, but when is redirected from the owncloud app to sigin it throws the error.

That indicates that the OIDC client configuration isn't correctly applied, I got the same error when my oidc client config was wrong

**Comment by juan11perez** [comment]
@gardar 
thank you. 
I added it to the opencloud.yml like this:

```
idp:
  ldap:
    bind_password: *****
  clients:
    - id: e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD
      name: ownCloud Android App
      trusted: false
      secret: ""
      redirect_uris:
        - oc://android.owncloud.com
      post_logout_redirect_uris:
        - oc://android.owncloud.com
      origins: []
      application_type: native    
```

appreciate some guidance.

**Comment by gardar** [comment]
That looks correct, although I have the default clients in my config too, not just the owncloud one. If the idp config is applied correctly then you should see it in the `data/idp/tmp/identifier-registration.yaml` file
Do you see any hits or errors in the logs when the owncloud client attempts to connect?
Are you sure you are using the embedded idp or perhaps a external one like keycloak?

**Comment by juan11perez** [comment]
thank you.
I see this in the identifier-registration.yaml
```
clients:
- id: OwnCloudAndroid
  name: ownCloud Android App
  trusted: false
  secret: ""
  redirect_uris:
  - oc://android.owncloud.com
  - https://mydomain.com/oidc-callback.html
  - https://mydomain.com/oidc-silent-redirect.html
  post_logout_redirect_uris:
  - oc://android.owncloud.com
  origins:
  - https://mydomain.com
  application_type: native
```

Im using idp. I have not activated keycloak.

I see this in the log
2025-07-19T15:00:51Z INF access-log | service=proxy proto=HTTP/1.1 request-id=0e101aaed300/qMsw6f6QbT-000298 traceid=152c22ae4848a65c7963164f4d8545d0 remote-addr=000.29.199.28 method=POST status=400 path=/signin/v1/identifier/_/logon duration=93.54658 bytes=102 line=github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/accesslog.go:34

**Comment by gardar** [comment]
Those `redirect_uris` are probably what's causing the issue, I think the owncloud client should only have the `- oc://android.owncloud.com` client.

I suspect that what's happening is that when you only have that single client under `clients:` in your `opencloud.yml` then it's overwriting all the default clients and opencloud adds those redirect_uris to your only client.

Try removing the `clients:` config block from your `opencloud.yml`, restart opencloud and take a look at the default entries that you get in the `identifier-registration.yaml` file, copy those and place them in your `opencloud.yml` file under the `clients` block and add the owncloud client config to it too.

For reference this is what my `identifier-registration.yaml` file looks like:

```yaml
clients:
- id: web
  name: OpenCloud Web App
  trusted: true
  secret: ""
  redirect_uris:
  - https://opencloud.example.com/
  - https://opencloud.example.com/oidc-callback.html
  - https://opencloud.example.com/oidc-silent-redirect.html
  post_logout_redirect_uris: []
  origins:
  - https://opencloud.example.com
  application_type: ""
- id: OpenCloudDesktop
  name: OpenCloud Desktop Client
  trusted: false
  secret: ""
  redirect_uris:
  - http://127.0.0.1
  - http://localhost
  post_logout_redirect_uris: []
  origins: []
  application_type: native
- id: OpenCloudAndroid
  name: OpenCloud Android App
  trusted: false
  secret: ""
  redirect_uris:
  - oc://android.opencloud.eu
  post_logout_redirect_uris:
  - oc://android.opencloud.eu
  origins: []
  application_type: native
- id: ownCloudAndroid
  name: ownCloud Android Client
  trusted: false
  secret: ""
  redirect_uris:
  - oc://android.owncloud.com
  post_logout_redirect_uris:
  - oc://android.owncloud.com
  origins: []
  application_type: native
- id: e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD
  name: ownCloud Android App
  trusted: false
  secret: ""
  redirect_uris:
  - oc://android.owncloud.com
  post_logout_redirect_uris:
  - oc://android.owncloud.com
  origins: []
  application_type: native
- id: OpenCloudIOS
  name: OpenCloud iOS App
  trusted: false
  secret: ""
  redirect_uris:
  - oc://ios.opencloud.eu
  post_logout_redirect_uris:
  - oc://ios.opencloud.eu
  origins: []
  application_type: native
```
